apiVersion: v1
kind: Service
metadata:
  name: {{ include "inforiver.name" . }}-api-service
  namespace: {{ include "inforiver.name" . }}
spec:
  selector:
    app: {{ include "inforiver.name" . }}-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.ports.sourcePort }}
    targetPort: {{ .Values.ports.containerPort }}